import './globals.css'


export const metadata = {
  title: 'Yusuf AL',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
        <body>{children}</body>
    </html>
  )
}
